external_components:
  - source:
      type: local
      path: components/esphome-idasen-desk-controller/components
  # - source: github://duchu-net/esphome-timotion-desk-controller@v1.0.0

esphome:
  name: esphome-ble-stand-up
  libraries:
    - 'ESP32 BLE Arduino'

esp32:
  board: esp32dev
  framework:
    # type: esp-idf
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: 'Esphome-Web-B489A8'
    password: 'L2i5rbTy5Fa7'
# captive_portal:

globals:
  # To store the Desk Connection Status
  - id: ble_client_connected
    type: bool
    initial_value: 'false'

# BEGIN BLUETOOTH DISCOVERY INTEGRATION
esp32_ble_tracker:
ble_client:
  - mac_address: 'CA:A6:27:CF:F8:EE' # Replace with the desk bluetooth mac address
    id: timotion_desk
    on_connect:
      then:
        - lambda: |-
            id(ble_client_connected) = true;
        - delay: 5s
        - lambda: |-
            id(desk_move).update();
            id(desk_height).update();
    on_disconnect:
      then:
        - lambda: |-
            id(ble_client_connected) = false;

idasen_desk_controller:
  ble_client_id: timotion_desk
  # Optional -- todo remove
  only_up_down_command: true

cover:
  - platform: idasen_desk_controller
    name: 'Desk'

sensor:
  # Desk Height Sensor
  - platform: ble_client
    type: characteristic
    ble_client_id: idasen_desk
    id: desk_height
    name: 'Desk Height'
    service_uuid: '6e400001-b5a3-f393-e0a9-e50e24dcca9e'
    characteristic_uuid: '6e400003-b5a3-f393-e0a9-e50e24dcca9e'
    icon: 'mdi:arrow-up-down'
    unit_of_measurement: 'cm'
    accuracy_decimals: 1
    update_interval: never
    notify: true
    # filters:
    #   - lambda: |- 
    #       static float last_value = NAN;
    #       if (x != last_value) {
    #         last_value = x;
    #         return x;    
    #       }
    #       return {};
    # or just delta filter :D
    filters:
      - delta: 0.1
    lambda: |-
      uint16_t raw_height = x[3];
      unsigned short height_mm = raw_height;
      return (float) height_mm;

  # Desk Speed Sensor
  - platform: ble_client
    type: characteristic
    ble_client_id: timotion_desk
    id: desk_move
    name: 'Desk Move'
    service_uuid: '6e400001-b5a3-f393-e0a9-e50e24dcca9e'
    characteristic_uuid: '6e400003-b5a3-f393-e0a9-e50e24dcca9e'
    icon: 'mdi:arrow-split-horizontal'
    accuracy_decimals: 0
    update_interval: never
    notify: true
    filters:
      - delta: 0.1
    lambda: |-
      uint16_t raw_speed = x[1];
      if (raw_speed == 65) return -1;
      if (raw_speed == 66) return 1;
      return 0;

binary_sensor:
  # Desk Bluetooth Connection Status
  - platform: template
    name: 'Desk Connection'
    icon: 'mdi:bluetooth'
    id: desk_connection
    lambda: 'return id(ble_client_connected);'

  # Desk Moving Status
  - platform: template
    name: 'Desk Moving'
    id: desk_moving
    icon: 'mdi:engine'
    lambda: 'return abs(id(desk_move).state) == 1;'
    # lambda: |-
    #   if (id(desk_move).state >= -1 && id(desk_move).state <= 1) return abs(id(desk_move).state) == 1; 
    #   return invalid;
